project_id = "ilnkeilltvkceohcjfjy"

[functions.safelist-analyze]
verify_jwt = false

[functions.safelist-studio]
verify_jwt = false

[functions.safevin-coach]
verify_jwt = false

[functions.generate-filter-text]
verify_jwt = false
